name: saltstack-dnsmasq-formula
source: https://github.com/bechtoldt/saltstack-dnsmasq-formula
summary: SaltStack Formula to set up and configure dnsmasq, a lightweight server providing DNS, DHCP and more
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
